# Generated by Django 3.0.2 on 2020-05-23 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 24, 2, 25, 4, 309842)),
        ),
    ]
